version: "2"

services:
  micro-frontend-test-page:
    container_name: micro-frontend-test-page
    build: test-page
    networks:
      - local-network
    environment:
      - NODE_ENV=production
      - PORT=3000
    tty: true

  micro-frontend-home-page:
    container_name: micro-frontend-home-page
    build: home-page
    networks:
      - local-network
    environment:
      - NODE_ENV=production
      - PORT=5000

  micro-frontend-nginx:
    container_name: micro-frontend-nginx
    build: nginx
    volumes:
      - ./assets:/var/www
    ports:
      - "8888:80"
    networks:
      - local-network
    ports:
      - "8888:80"
    links:
      - micro-frontend-test-page
    depends_on:
      - micro-frontend-test-page
      - micro-frontend-home-page

networks:
  local-network:
